development:
  secret_key_base: '95182ec21cccb3c5ca9425bb8a45ec9327ae7e33e857395b689f38fc6d801e1185c7abb662190c2b8512f05e8087f0bab0f604f802b4c631431811b5b1d32a29'
  fk_auth_url: 'http://fkgent.be/api_isengard_v2.php'
  fk_auth_salt: '#development#'
  fk_auth_key: '#development#'
  enrolment_key: '#development#'
  omniauth_client_id: 'tomtest'
  omniauth_client_secret: 'blargh'

test:
  secret_key_base: '95182ec21cccb3c5ca9425bb8a45ec9327ae7e33e857395b689f38fc6d801e1185c7abb662190c2b8512f05e8087f0bab0f604f802b4c631431811b5b1d32a29'
  fk_auth_url: 'http://fkgent.be/api_isengard_v2.php'
  fk_auth_salt: '#development#'
  fk_auth_key: '#development#'
  enrolment_key: '#development#'

production:
  secret_key_base: 'a27fcd9aa2eabd14030493d6b5a1521ba09c9d23a1dd90b3c9d6914b8d226d1df8b46af3005f73a29c3ef1acd86de3669fbe08605d9ce8da73856c734f8a0e36'
  fk_auth_url: 'http://fkgent.be/api_isengard_v2.php'
  fk_auth_salt: '#development#'
  fk_auth_key: '#development#'
  enrolment_key: '#development#'
  omniauth_client_id: ''
  omniauth_client_secret: ''
